spring:
  application:
    name: Saphire

  # Database
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:saphire_system}
    username: ${DB_USERNAME:saphire_master}
    password: ${DB_PASSWORD:saphire_password}
    driver-class-name: org.postgresql.Driver

  # JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Database Migrations
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    baseline-version: 0
    locations: classpath:db/migration

  # Jackson (JSON)
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: ${TIMEZONE:Europe/Istanbul}

# Server
server:
  port: ${SERVER_PORT:8080}

# JWT Config
jwt:
  secret: ${JWT_SECRET:ee5ddc7600da0fc86d4bb16f5b3b4862c47c210bbb9f2c854e9b04cf9cfb6de3}
  expiration: ${JWT_EXPIRATION:28800000}

# Logging
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.crownbyte.saphire: ${LOG_LEVEL_APP:DEBUG}
    org.hibernate.SQL: ${LOG_LEVEL_SQL:DEBUG}